# Configurations to use when validating meta-lts-collab with CI

# Required to build libpam
DISTRO_FEATURES:append = " pam"

# Enables ptest
DISTRO_FEATURES:append = " ptest"
EXTRA_IMAGE_FEATURES:append = " ssh-server-openssh ptest-pkgs"
IMAGE_INSTALL:append = " ptest-runner"

# Enable automated testing
IMAGE_CLASSES += "testimage"
TEST_TARGET = "qemu"
TEST_SUITES = "ping ssh ptest"

# do_testimage configuration
TEST_RUNQEMUPARAMS += "kvm nographic slirp snapshot"
TEST_QEMUPARAMS += "-smp 8"
TEST_SERVER_IP = "127.0.0.1"
QB_CPU_KVM = "-cpu host"
QB_MEM = "-m 16384"
QEMU_USE_SLIRP = "1"

# Ensure there is enough space to run tests
IMAGE_OVERHEAD_FACTOR = "1.0"
IMAGE_ROOTFS_EXTRA_SPACE = "1124288"
