# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-lts-collab-test"
BBFILE_PATTERN_meta-lts-collab-test = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-lts-collab-test = "6"

LAYERDEPENDS_meta-lts-collab-test = "core meta-lts-collab"
LAYERSERIES_COMPAT_meta-lts-collab-test = "dunfell"
