---
name: Bitbake Common Steps
on:  # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
      only-build-modified:
        required: true
        type: boolean
      parse-only:
        required: true
        type: boolean
      runner:
        required: true
        type: string

jobs:
  bitbake:
    runs-on: ${{ inputs.runner }}
    steps:
      - name: Clone meta-lts-collab
        uses: actions/checkout@v5
        with:
          path: ./meta-lts-collab

      - name: Clone poky (${{ inputs.branch }})
        uses: actions/checkout@v5
        with:
          repository: yoctoproject/poky
          ref: ${{ inputs.branch }}
          path: ./poky

      - name: Clone meta-oe (${{ inputs.branch }})
        uses: actions/checkout@v5
        with:
          repository: openembedded/meta-openembedded
          ref: ${{ inputs.branch }}
          path: ./meta-oe

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            gawk wget git-core diffstat unzip texinfo gcc-multilib \
            build-essential chrpath socat cpio python3 python3-pip \
            python3-pexpect xz-utils debianutils iputils-ping python3-git \
            python3-jinja2 libegl1-mesa libsdl1.2-dev pylint xterm \
            python3-subunit mesa-common-dev

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@24d32ffd492484c1d75e0c0b894501ddb9d30d62  # v47

      - name: Get build targets
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        id: targets
        run: |
          if [ "${{ inputs.only-build-modified }}" = "false" ]; then
            ALL_CHANGED_FILES=""
          fi
          TARGETS=$(
            $GITHUB_WORKSPACE/meta-lts-collab/scripts/get-bitbake-targets.py \
              $ALL_CHANGED_FILES
          )
          echo "build_targets=$TARGETS" >> $GITHUB_OUTPUT

      - name: Setup and run bitbake
        if: ${{ steps.targets.outputs.build_targets != '' }}
        run: |
          # Source build environment
          source poky/oe-init-build-env

          # Add all layers
          bitbake-layers add-layer $GITHUB_WORKSPACE/meta-oe/meta-*
          bitbake-layers add-layer $GITHUB_WORKSPACE/meta-lts-collab
          bitbake-layers show-layers

          # Add configurations
          echo 'DISTRO_FEATURES:append = " pam"' >> conf/auto.conf

          # Run bitbake
          extra_args=""
          if [ "${{ inputs.parse-only }}" = "true" ]; then
            extra_args="--parse-only"
          fi
          bitbake $extra_args ${{ steps.targets.outputs.build_targets }}
