---
name: Lint Common Steps
on:  # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      runner:
        default: ubuntu-22.04
        description: 'The runner to execute this workfow with'
        required: false
        type: string

permissions:
  contents: read

jobs:
  lint:
    name: 'Lint scripts & CI'
    runs-on: ${{ inputs.runner }}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0

      - name: Set up Python
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1  # v6.3.0
        with:
          python-version: '3.10'

      - name: Install tools
        run: pip install -r requirements-dev.txt

      - name: Run ruff check on scripts
        run: ruff check scripts

      - name: Run ruff format on scripts
        run: ruff format scripts/

      - name: Run yamllint on workflows
        run: yamllint .github/workflows/

      - name: Run oelint-adv
        run: oelint-adv $(find -name '*.bb' -o -name '*.bbappend' -o -name '*.conf')
