---
name: 'Push & Periodic'

on:  # yamllint disable-line rule:truthy
  push:
    branches: ["dunfell"]
  schedule:
    - cron: " 0 3 * * SUN"

permissions:
  contents: read

jobs:
  lint:
    uses: ./.github/workflows/lint-common.yml

  parse:
    needs: lint
    uses: ./.github/workflows/bitbake-common.yml
    with:
      branch: ${{ github.ref_name }}
      only-build-modified: false
      parse-only: true
      runner: ubuntu-22.04
      use-cache: false

  clear-cache:  # We will always need to clear out the cache until more cache space is available
    permissions:
      actions: write
    uses: ./.github/workflows/clear-cache.yml
    with:
      cache-key: downloads-and-sstate-${{ github.ref_name }}

  build:
    needs: [parse, clear-cache]
    uses: ./.github/workflows/bitbake-common.yml
    with:
      branch: ${{ github.ref_name }}
      only-build-modified: false
      parse-only: false
      runner: yocto_build_host
      save-cache: true
