---
name: Push
on:  # yamllint disable-line rule:truthy
  push:
    branches: ["kirkstone"]

permissions:
  contents: read
  id-token: write
  pages: write

jobs:
  common:
    name: "Common"
    uses: ./.github/workflows/_common.yml
    with:
      run-tests: false
