---
name: Weekly
on:  # yamllint disable-line rule:truthy
  schedule:
    - cron: "0 3 * * SUN"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  periodic:
    name: Lint
    uses: ./.github/workflows/_periodic.yml
