name: Yocto Check Layer

on:
  workflow_call:
    inputs:
      branch:
        description: 'The Yocto branch to run yocto-check-layer against'
        required: true
        type: string
      runner:
        description: 'The runner to execute this workflow with'
        required: true
        type: string

permissions:
  contents: read

jobs:
  yocto-check-layer:
    runs-on: ${{ inputs.runner }}
    steps:
      - name: Clone meta-lts-collab
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
        with:
          ref: ${{ inputs.branch }}
          path: ${{ github.workspace }}/meta-lts-collab

      - name: Clone poky (${{ inputs.branch }})
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
        with:
          repository: yoctoproject/poky
          ref: ${{ inputs.branch }}
          path: ${{ github.workspace }}/poky

      - name: Clone meta-oe (${{ inputs.branch }})
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
        with:
          repository: openembedded/meta-openembedded
          ref: ${{ inputs.branch }}
          path: ${{ github.workspace }}/meta-oe

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            gawk wget git-core diffstat unzip texinfo gcc-multilib \
            build-essential chrpath socat cpio python3 python3-pip \
            python3-pexpect xz-utils debianutils iputils-ping python3-git \
            python3-jinja2 libegl1-mesa libsdl1.2-dev pylint xterm \
            python3-subunit mesa-common-dev

      - name: Setup and run yocto-check-layer
        if: ${{ steps.targets.outputs.all_build_targets != '' }}
        run: |
          # Source build environment
          source poky/oe-init-build-env

          # Add all layers
          bitbake-layers add-layer $GITHUB_WORKSPACE/meta-oe/meta-*
          bitbake-layers show-layers

          # Run yocto-check-layer
          yocto-check-layer \
            --without-software-layer-signature-check
            $GITHUB_WORKSPACE/meta-lts-collab
